#!/usr/bin/with-contenv bash

cd /app

shopt -s globstar

umask 022

mangal config set -k metadata.comic_info_xml --value true
mangal config set -k metadata.fetch_anilist --value true
mangal config set -k metadata.series_json --value true
mangal config set -k formats.use --value "cbz"
mangal config set -k downloader.download_cover --value true
mangal config set -k downloader.redownload_existing --value true
mangal config set -k downloader.chapter_name_template --value "[{padded-index}] {chapter}"
mangal config set -k downloader.create_manga_dir --value true
mangal config set -k downloader.create_volume_dir --value false
mangal config set -k downloader.stop_on_error --value true
mangal config set -k downloader.path --value '.'

exec 2>&1
exec s6-setuidgid abc /usr/bin/node dist/server/index.js
